change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Change log:
  categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore

  $CHANGES
