language: bash
sudo: required

script:
    - sudo apt-get install jq -y
    - echo "Making connection using github api"
    - wget -O gistbackup.sh https://gist.githubusercontent.com/hemanth22/195b4e3142c1b9ec961d1a81967171c3/raw/47c1f6c079376655dd68f9152f5c7d167ee3a3a1/backupgist.sh
    - chmod 777 gistbackup.sh
    - ./gistbackup.sh

after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/CreateIssue
    - chmod 777 createIssue.sh
    - ./createIssue.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
