language: bash
sudo: required

script:
    - echo "Downloading jq."
    - sudo apt-get install jq -y
    - echo "Making connection using github api"
    - wget -O gistbackup.sh https://gist.githubusercontent.com/hemanth22/195b4e3142c1b9ec961d1a81967171c3/raw/0b13137f19a7bba56fb73493aa729589bea0d478/backupgist.sh
    - chmod 777 gistbackup.sh
    - ./gistbackup.sh
    - cat gist.backup

after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/CreateIssue
    - chmod 777 createIssue.sh
    - ./createIssue.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
