language: bash
sudo: required

script:
    - echo "Downloading jq."
    - sudo apt-get install jq -y
    - echo "Making connection using github api"
    - wget -O backupgist.sh https://gist.githubusercontent.com/hemanth22/195b4e3142c1b9ec961d1a81967171c3/raw/eded6ada1c049827cade39a29c72ba22e625677c/
    - chmod 777 backupgist.sh
    - ./backupgist.sh | jq -r '.[].files[].raw_url' > gist.backup
    - cat gist.backup

after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/CreateIssue
    - chmod 777 createIssue.sh
    - ./createIssue.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
