language: bash
sudo: required

script:
    - echo "Downloading jq."
    - sudo apt-get install jq -y
    - echo "Making connection using github api"
    - wget -O backupgist.sh https://gist.githubusercontent.com/hemanth22/70dd305f1827c838c2bb3fc781c3e163/raw/e71032891b5883deefdeccfa0e85aa46e3555fe2/backuptest.sh
    - chmod 777 backupgist.sh
    - ./backupgist.sh > list
    - cat list
    - cat list | jq -r .[].files[].raw_url > gist.backup
    - cat gist.backup

after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/CreateIssue
    - chmod 777 createIssue.sh
    - ./createIssue.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
